build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated: ['Composable']
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 8
    ignoreAnnotated: ['Composable']
  LargeClass:
    active: true
    threshold: 600

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes: ['**/data/**', '**/presentation/payment/**']
  SwallowedException:
    active: true
    excludes: ['**/data/**', '**/presentation/payment/**']

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100']
    ignoreAnnotated: ['Composable']
    excludes: ['**/ui/theme/**', '**/test/**']
  MaxLineLength:
    active: true
    maxLineLength: 160
    excludes: ['**/test/**']
  WildcardImport:
    active: true
  ReturnCount:
    active: true
    max: 3